### ISSUE TITLE
sbi_detector config problem

### ISSUE THREAD

**Issue by Ftgn-dpA** [YZY-stack/DF40#19]
Could you please let me know why the backbone_config num_classes in sbi.yaml is not set to 2? This seems to cause an error when running the sbi_detector. Thank you!
```yaml
backbone_config:
  mode: original
  num_classes: 4  # Runs fine at 2
  inc: 3
  dropout: false
  pretrained: true
```
